/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ma.fstm.ilisi2.projects.biblio.view;

import ma.fstm.ilisi2.projects.biblio.controler.Bibliotheque;
import ma.fstm.ilisi2.projects.biblio.model.bo.Livre;

import javax.swing.table.DefaultTableModel;
import java.util.concurrent.atomic.AtomicReference;

/**
 * @author ilisi
 */
public class FrLivre extends javax.swing.JFrame {


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnAdd;
   private javax.swing.JButton btnDel;
   private javax.swing.JButton btnMdf;
   private javax.swing.JButton btnResh;
   private javax.swing.Box.Filler filler1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane scroll;
   private javax.swing.JTable tblLivres;
   private javax.swing.JTextField txtISBN;
   private javax.swing.JTextField txtTitre;
   private AtomicReference<Livre> selectedLivre = new AtomicReference<>();

   /**
    * Creates new form FrLivre
    */
   public FrLivre() {
      initComponents();
   }

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(FrLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(FrLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(FrLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(FrLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new FrLivre().setVisible(true);
         }
      });
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      scroll = new javax.swing.JScrollPane();
      tblLivres = new javax.swing.JTable();
      jLabel3 = new javax.swing.JLabel();
      jPanel1 = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      txtTitre = new javax.swing.JTextField();
      filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
      jLabel1 = new javax.swing.JLabel();
      txtISBN = new javax.swing.JTextField();
      jPanel2 = new javax.swing.JPanel();
      btnResh = new javax.swing.JButton();
      btnDel = new javax.swing.JButton();
      btnMdf = new javax.swing.JButton();
      btnAdd = new javax.swing.JButton();


      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      addWindowListener(new java.awt.event.WindowAdapter() {
         public void windowOpened(java.awt.event.WindowEvent evt) {
            formWindowOpened(evt);
         }
      });

      tblLivres.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblLivresMouseClicked(evt);
         }
      });
      scroll.setViewportView(tblLivres);

      jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
      jLabel3.setText("Liste des livres :");

      jPanel1.setLayout(new java.awt.GridLayout(1, 0));

      jLabel2.setText("titre");
      jPanel1.add(jLabel2);

      txtTitre.setText("jTextField2");
      jPanel1.add(txtTitre);
      jPanel1.add(filler1);

      jLabel1.setText("isbn");
      jPanel1.add(jLabel1);

      txtISBN.setText("jTextField1");

      jPanel1.add(txtISBN);

      jPanel2.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

      btnResh.setText("Refresh");
      btnResh.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnReshActionPerformed(evt);
         }
      });
      jPanel2.add(btnResh);

      btnDel.setText("Supprimer");
      btnDel.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnDelActionPerformed(evt);
         }
      });
      jPanel2.add(btnDel);

      btnMdf.setText("Modifier");
      btnMdf.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnMdfActionPerformed(evt);
         }
      });
      jPanel2.add(btnMdf);

      btnAdd.setText("AJOUTER");
      btnAdd.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAddActionPerformed(evt);
         }
      });
      jPanel2.add(btnAdd);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                      .addGroup(layout.createSequentialGroup()
                                              .addContainerGap()
                                              .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addGroup(layout.createSequentialGroup()
                                              .addContainerGap()
                                              .addComponent(jLabel3))
                                      .addGroup(layout.createSequentialGroup()
                                              .addGap(34, 34, 34)
                                              .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addGroup(layout.createSequentialGroup()
                                              .addGap(59, 59, 59)
                                              .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addGap(24, 24, 24)
                              .addComponent(jLabel3)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(29, 29, 29)
                              .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addContainerGap(46, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      // TODO add your handling code here:
      if (Bibliotheque.ajouterLivre(txtISBN.getText(), txtTitre.getText())) {
         afficherLivres();
      }
   }//GEN-LAST:event_btnAddActionPerformed

   private int getSelectedLivreId() {
      int row = tblLivres.getSelectedRow();
      if (row != -1) {
         Object id = ((DefaultTableModel) tblLivres.getModel()).getValueAt(row, 0);
         return Integer.parseInt(id.toString());
      }
      return -1;
   }

   private Livre getSelectedLivre() {
      int row = tblLivres.getSelectedRow();
      if (row != -1) {
         Object id = ((DefaultTableModel) tblLivres.getModel()).getValueAt(row, 0);
         Object isbn = ((DefaultTableModel) tblLivres.getModel()).getValueAt(row, 1);
         Object titre = ((DefaultTableModel) tblLivres.getModel()).getValueAt(row, 2);
         return new Livre(Integer.parseInt(id.toString()), isbn.toString(), titre.toString());
      }
      return null;
   }

   private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
      // TODO add your handling code here:
      Bibliotheque.supprimerLivre(getSelectedLivreId());
      afficherLivres();
      tblLivres.clearSelection();
      txtISBN.setText("");
      txtTitre.setText("");
   }//GEN-LAST:event_btnDelActionPerformed

   private void btnMdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMdfActionPerformed
      // TODO add your handling code here:
      Bibliotheque.updateLivre(selectedLivre.get().getId(), txtISBN.getText(), txtTitre.getText());
      afficherLivres();
      tblLivres.clearSelection();
      txtISBN.setText("");
      txtTitre.setText("");
   }//GEN-LAST:event_btnMdfActionPerformed

   private void btnReshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReshActionPerformed
      // TODO add your handling code here:
      afficherLivres();
   }//GEN-LAST:event_btnReshActionPerformed

   private void tblLivresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLivresMouseClicked
      // TODO add your handling code here:
      selectedLivre.set(getSelectedLivre());
      boolean isSelecting = selectedLivre.get() != null;
      if (isSelecting) {
         txtISBN.setText(selectedLivre.get().getIsbn());
         txtTitre.setText(selectedLivre.get().getTitre());
      }
      btnDel.setEnabled(isSelecting);
      btnMdf.setEnabled(isSelecting);
   }//GEN-LAST:event_tblLivresMouseClicked

   private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      // TODO add your handling code here:
      afficherLivres();
   }//GEN-LAST:event_formWindowOpened

   private void afficherLivres() {
      Bibliotheque.afficherLives((DefaultTableModel) tblLivres.getModel());
   }
   // End of variables declaration//GEN-END:variables
}
